# Generated by Django 5.2.8 on 2025-11-27 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0003_university_description_alter_university_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='photo',
        ),
    ]
