# Generated by Django 5.2.8 on 2025-11-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0004_remove_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students_photos/'),
        ),
    ]
